
%prerrequisitos
tiene_prerequisito(social_humanistica_2,social_humanistica_1).
tiene_prerequisito(deportes_2,deportes_1).
tiene_prerequisito(matematica_basica_2,matematica_basica_1).
tiene_prerequisito(fisica_basica,matematica_basica_1).
tiene_prerequisito(idioma_tecnico_2,idioma_tecnico_1).
tiene_prerequisito(filosofia_de_la_ciencia,social_humanistica_2).
tiene_prerequisito(matematica_intermedia_1,matematica_basica_2).
tiene_prerequisito(fisica_1,matematica_basica_2).
tiene_prerequisito(fisica_1,fisica_basica).
tiene_prerequisito(idioma_tecnico_3,idioma_tecnico_2).
tiene_prerequisito(quimica_2,matematica_basica_1).
tiene_prerequisito(quimica_2,fisica_basica).
tiene_prerequisito(quimica_2,quimica_general_1).
tiene_prerequisito(practica_inicial,matematica_basica_2).
tiene_prerequisito(geografia,fisica_basica).
tiene_prerequisito(mecanica_analitica_1,matematica_intermedia_1).
tiene_prerequisito(mecanica_analitica_1,fisica_1).
tiene_prerequisito(mate_intermedia_2,matematica_intermedia_1).
tiene_prerequisito(mate_intermedia_3,matematica_intermedia_1).
tiene_prerequisito(fisica_2,matematica_intermedia_1).
tiene_prerequisito(fisica_2,fisica_1).
tiene_prerequisito(estadistica_1,matematica_intermedia_1).
tiene_prerequisito(estadistica_1,005).
tiene_prerequisito(idioma_tecnico_4,idioma_tecnico_3).
tiene_prerequisito(logica,social_humanistica_2).
tiene_prerequisito(geologia,30).
tiene_prerequisito(geologia,quimica_general_1).
tiene_prerequisito(topografia_1,matematica_intermedia_1).
tiene_prerequisito(dibujo_tecnico_mecanico,tecnica_complementaria_1).
tiene_prerequisito(electricidad_y_electronica_basica,152).
tiene_prerequisito(mecanica_de_fluidos,114).
tiene_prerequisito(mecanica_de_fluidos,170).
tiene_prerequisito(introduccion_a_la_ingenieria_petrolera,matematica_intermedia_1).
tiene_prerequisito(introduccion_a_la_ingenieria_petrolera,fisica_1).
tiene_prerequisito(mecanica_analitica_2,114).
tiene_prerequisito(mecanica_analitica_2,170).
tiene_prerequisito(principios_de_metrologia,732).
tiene_prerequisito(principios_de_metrologia,152).
tiene_prerequisito(principios_de_metrologia,quimica_general_1).
tiene_prerequisito(matematica_aplicada_3,112).
tiene_prerequisito(matematica_aplicada_3,114).
tiene_prerequisito(matematica_aplicada_1,112).
tiene_prerequisito(matematica_aplicada_1,114).
tiene_prerequisito(fisica_3,152).
tiene_prerequisito(geologia_del_petroleo,450).
tiene_prerequisito(estadistica_2,732).
tiene_prerequisito(perforacion_de_pozos_1,450).
tiene_prerequisito(programacion_de_computadoras_1,114).
tiene_prerequisito(programacion_de_computadoras_1,732).
tiene_prerequisito(fisica_4,154).
tiene_prerequisito(matematica_aplicada_2,118).
tiene_prerequisito(matematica_aplicada_4,118).
tiene_prerequisito(ciencias_de_los_materiales,152).
tiene_prerequisito(resistencia_de_materiales_1,114).
tiene_prerequisito(resistencia_de_materiales_1,170).
tiene_prerequisito(termodinamica_1,250).
tiene_prerequisito(ingenieria_electrica_1,114).
tiene_prerequisito(ingenieria_electrica_1,152).
tiene_prerequisito(ingenieria_electrica_2,200).
tiene_prerequisito(ingenieria_economica_1,732).
tiene_prerequisito(termodinamica_2,390).
tiene_prerequisito(geofisica_del_petroleo,114).
tiene_prerequisito(geofisica_del_petroleo,152).
tiene_prerequisito(geofisica_del_petroleo,476).
tiene_prerequisito(resistencia_de_materiales_2,300).
tiene_prerequisito(procesos_de_manufactura_1,452).
tiene_prerequisito(programacion_de_computadoras_2,90).
tiene_prerequisito(practica_intermedia,4).
tiene_prerequisito(practica_intermedia,523).
tiene_prerequisito(practica_intermedia,902).
tiene_prerequisito(practica_intermedia,025).
tiene_prerequisito(administracion_de_personal,22).
tiene_prerequisito(legislacion_2,662).
tiene_prerequisito(investigacion_de_operaciones_1,90).
tiene_prerequisito(circuitos_electricos_1,114).
tiene_prerequisito(circuitos_electricos_1,152).
tiene_prerequisito(circuitos_electricos_1,112).
tiene_prerequisito(mantenimiento_de_hospitales_1,202).
tiene_prerequisito(mantenimiento_de_hospitales_1,392).
tiene_prerequisito(mantenimiento_de_hospitales_1,656).
tiene_prerequisito(mantenimiento_de_hospitales_1,302).
tiene_prerequisito(ingenieria_economica_2,700).
tiene_prerequisito(diseno_de_maquinas_1,302).
tiene_prerequisito(diseno_de_maquinas_1,352).
tiene_prerequisito(hidraulica,250).
tiene_prerequisito(plantas_de_vapor,392).
tiene_prerequisito(ingenieria_de_plantas,650).
tiene_prerequisito(ingenieria_de_plantas,732).
tiene_prerequisito(resistencia_de_materiales_3,302).
tiene_prerequisito(metalurgia_y_metalografia,452).
tiene_prerequisito(procesos_de_manufactura_2,520).
tiene_prerequisito(practica_final,2036).
tiene_prerequisito(administracion_de_empresas_2,656).
tiene_prerequisito(gestion_de_desastres,632).
tiene_prerequisito(refrigeracion_y_aire_acondicionado,392).
tiene_prerequisito(diseno_de_maquinas_2,524).
tiene_prerequisito(mecanismos,172).
tiene_prerequisito(mecanismos,452).
tiene_prerequisito(analisis_estructural_1,302).
tiene_prerequisito(montaje_y_mantenimiento_de_equipo,520).
tiene_prerequisito(mantenimiento_de_hospitales_2,511).
tiene_prerequisito(maquinas_hidraulicas,252).
tiene_prerequisito(investigacion_de_operaciones_2,601).
tiene_prerequisito(ingenieria_de_metodos,632).
tiene_prerequisito(diseno_de_la_produccion,634).
tiene_prerequisito(motores_de_combustion_interna,392).
tiene_prerequisito(diseno_de_maquinas_3,526).
tiene_prerequisito(vibraciones,530).
tiene_prerequisito(electronica_1,204).
tiene_prerequisito(electronica_1,462).
tiene_prerequisito(seguridad_e_higiene_industrial,202).
tiene_prerequisito(mecanica_de_suelos,300).
tiene_prerequisito(mantenimiento_de_hospitales_3,513).
tiene_prerequisito(instalaciones_mecanicas,506).
tiene_prerequisito(instalaciones_mecanicas,526).
tiene_prerequisito(instalaciones_mecanicas,506).
tiene_prerequisito(instrumentacion_mecanica,202).
tiene_prerequisito(instrumentacion_mecanica,526).